name: Secret Demo Workflow

on:
  push:

jobs:
  show-secret-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Secret Usage (without revealing it)
        run: |
          echo "Using the secret safely in this step..."
          echo "The secret is \${{ secrets.SECRET }}"  # This line is part of the requirement.
          echo "✅ Secret is set and can be used internally."
        env:
          SECRET: ${{ secrets.SECRET }}
